services:
  backend-app:
    container_name: backend-app-suml
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    networks:
      - suml-app-network
  vite-client-suml:
    container_name: test-vite-client-suml
    build:
      context: ./vite-client-suml
      dockerfile: ./Dockerfile
    ports:
      - "4400:80"
    networks:
      - suml-app-network

networks:
  suml-app-network:
    driver: bridge
  